### ISSUE TITLE
Windows Executable path

### ISSUE THREAD

**Issue by jonszcz** [sfischer13/atom-linter-beancount#1]
I have this installed on Windows 10 and have Beancount working through both Cygwin and Ubuntu on Windows. I can get bean-check to run through cygwin, linux or the command line when I add C:\cygwin64\bin to the %PATH% but it doesn't seem to want to run in Atom. I'm tried updating the path to the executable in the Settings, but I'm unclear on which path I should be using.

**Comment by sfischer13** [comment]
In the settings, the full path to the `bean-check` executable should be given. Unfortunately, I do not have access to a Windows computer for checking Windows compatibility.
